//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int idPerson { get; set; }
        public string address1 { get; set; }
        public string number { get; set; }
        public string complement { get; set; }
        public string district { get; set; }
        public int idCity { get; set; }
        public string CEP { get; set; }
    
        public virtual City City { get; set; }
        public virtual Person Person { get; set; }
    }
}
