//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigPromotion
    {
        public int idPromotion { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dtStart { get; set; }
        public Nullable<System.DateTime> dtEnd { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
