//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuckyCode
    {
        public int idLuckyCode { get; set; }
        public int code { get; set; }
        public int idReceipt { get; set; }
        public Nullable<System.DateTime> dtWinner { get; set; }
        public Nullable<System.DateTime> dtRaffle { get; set; }
        public int idSerie { get; set; }
        public int serie { get; set; }
        public bool isWinner { get; set; }
    
        public virtual Receipt Receipt { get; set; }
    }
}
