//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsSending
    {
        public int idNewsSending { get; set; }
        public string Destination { get; set; }
        public string Subject { get; set; }
        public short Status { get; set; }
        public Nullable<System.DateTime> dtSending { get; set; }
        public string StatusDetail { get; set; }
        public Nullable<int> idReceipt { get; set; }
        public string fileName { get; set; }
        public Nullable<int> idPerson { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
