//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.NewsSending = new HashSet<NewsSending>();
        }
    
        public int idReceipt { get; set; }
        public int idPerson { get; set; }
        public int idProduct { get; set; }
        public bool isWinner { get; set; }
        public System.DateTime dtCreation { get; set; }
        public Nullable<bool> isValidated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsSending> NewsSending { get; set; }
        public virtual Person Person { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
