//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SequenceSeries
    {
        public int idSequenceSeries { get; set; }
        public int idSerie { get; set; }
        public int value { get; set; }
        public int ordem { get; set; }
        public int quant { get; set; }
    
        public virtual Series Series { get; set; }
    }
}
