//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public string CNPJ { get; set; }
        public string name { get; set; }
        public string IBM { get; set; }
        public string address { get; set; }
        public string district { get; set; }
        public string cityName { get; set; }
        public string CEP { get; set; }
        public string state { get; set; }
    }
}
