//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewReceiptExport
    {
        public int idReceipt { get; set; }
        public bool Premiado { get; set; }
        public Nullable<bool> Validado { get; set; }
        public string VoucherVinculado { get; set; }
        public System.DateTime Data_do_Cadastro_do_Recibo { get; set; }
        public string Nome_do_Participante { get; set; }
        public string cpf { get; set; }
        public string email { get; set; }
        public System.DateTime Data_de_Cadastro_do_Participante { get; set; }
    }
}
