//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewReceiptExport
    {
        public int idReceipt { get; set; }
        public string CNPJ_do_estabelecimento { get; set; }
        public string Produto { get; set; }
        public string Tipo_do_Produto { get; set; }
        public bool Premiado { get; set; }
        public Nullable<bool> Validado { get; set; }
        public string Motivo_da_Validacao { get; set; }
        public System.DateTime Data_do_Cadastro_do_Recibo { get; set; }
        public string Nome_do_Participante { get; set; }
        public string cpf { get; set; }
        public string nascimento { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string uf { get; set; }
        public string PersonCidade { get; set; }
        public string endereco { get; set; }
        public string PersonNumero { get; set; }
        public string PensonComplemento { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public System.DateTime Data_de_Cadastro_do_Participante { get; set; }
    }
}
