//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int idVoucher { get; set; }
        public Nullable<int> idPerson { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> dtWinner { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
