// <auto-generated />
namespace ShiftInc.Raizen.ShellTanqueCheio.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adminaccounttable2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adminaccounttable2));
        
        string IMigrationMetadata.Id
        {
            get { return "201606152119247_adminaccount-table2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
