//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Coupon.Entity.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymPass : DbContext
    {
        public GymPass()
            : base("name=GymPass")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminAccount> AdminAccount { get; set; }
        public virtual DbSet<NewsSending> NewsSending { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<ViewReceiptExport> ViewReceiptExport { get; set; }
        public virtual DbSet<Voucher> Voucher { get; set; }
        public virtual DbSet<ConfigPromotion> ConfigPromotion { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
    }
}
